name: CI Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/ci-backend.yml'
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
  GHCR: ghcr.io/${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  HELM_REPO: phanminhtri667/kltn_HR_managementkltn_helm


permissions:
  contents: write
  packages: write

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PASS_TOKEN }}

      - name: Build + Push backend
        run: |
          SAFE_REPO=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
          IMAGE_NAME="$GHCR/$SAFE_REPO-backend:${IMAGE_TAG}"
          docker build -t "$IMAGE_NAME" ./server
          docker push "$IMAGE_NAME"

  update-helm-backend:
    needs: build-and-push-backend
    runs-on: ubuntu-latest
    steps:
      - name: Clone Helm Repo
        run: |
          git clone https://x-access-token:${{ secrets.PASS_TOKEN }}@github.com/${{ env.HELM_REPO }}.git helm

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update image tag
        working-directory: helm/kltn
        run: |
          yq -i ".backend.image.tag = \"${IMAGE_TAG}\"" values.yaml

      - name: Commit & push
        working-directory: helm
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add kltn/values.yaml
          git commit -m "Update backend tag to ${IMAGE_TAG}" || echo "No changes"
          git push https://x-access-token:${{ secrets.PASS_TOKEN }}@github.com/${{ env.HELM_REPO }}.git HEAD:main
